import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useFieldArray } from "react-hook-form";
const Education = ({ register, errors, handleSubmit, onSubmit, control }) => {
    const { fields, append, remove } = useFieldArray({
        control,
        name: "educations"
    });
    return (_jsxs("form", { onSubmit: handleSubmit(onSubmit), className: "form-shell", children: [_jsx("h2", { className: "text-2xl font-bold mb-4", children: "Education" }), fields.map((field, index) => (_jsxs("div", { className: "form-section", children: [_jsxs("div", { children: [_jsx("label", { className: "block text-xs font-semibold", children: "Degree" }), _jsx("input", { ...register(`educations.${index}.degree`, { required: "Degree is required" }), className: "w-full border rounded-md p-2", placeholder: "e.g., Bachelor of Science" }), errors.educations?.[index]?.degree && (_jsx("p", { className: "text-red-500 text-xs", children: errors.educations[index]?.degree?.message }))] }), _jsxs("div", { children: [_jsx("label", { className: "block text-xs font-semibold", children: "School" }), _jsx("input", { ...register(`educations.${index}.school`, { required: "School is required" }), className: "w-full border rounded-md p-2", placeholder: "e.g., University of Bucharest" }), errors.educations?.[index]?.school && (_jsx("p", { className: "text-red-500 text-xs", children: errors.educations[index]?.school?.message }))] }), _jsxs("div", { className: "flex gap-4", children: [_jsxs("div", { children: [_jsx("label", { className: "block text-xs font-semibold", children: "Start Date" }), _jsx("input", { type: "date", ...register(`educations.${index}.startDate`, { required: "Start date is required" }), className: "w-full border rounded-md p-2" }), errors.educations?.[index]?.startDate && (_jsx("p", { className: "text-red-500 text-xs", children: errors.educations[index]?.startDate?.message }))] }), _jsxs("div", { children: [_jsx("label", { className: "block text-xs font-semibold", children: "End Date" }), _jsx("input", { type: "date", ...register(`educations.${index}.endDate`), className: "w-full border rounded-md p-2" })] })] }), _jsx("button", { type: "button", onClick: () => remove(index), className: "mt-2 text-red-500 hover:underline text-sm", children: "Remove Education" })] }, field.id))), _jsx("button", { type: "button", onClick: () => append({ degree: "", school: "", startDate: "", endDate: "" }), className: "mt-4 bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600", children: "+ Add Another Education" })] }));
};
export default Education;
